export type ToolEditorial = {
  image: string;
  alt: string;
  answer: string;
  method: string;
  caution: string;
  relatedLabel: string;
  relatedHref: string;
};

export const toolEditorial: Record<string, ToolEditorial> = {
  'gain-temps': { image: '/images/iapmesuisse-outil-gain-temps-20260909.png', alt: 'Dirigeant de PME suisse organisant ses tâches de travail à son bureau.', answer: 'Calculez le temps potentiellement libéré par une tâche répétitive avant de choisir un logiciel ou un projet.', method: 'Indiquez la fréquence et la durée réelle. Gardez l’estimation comme point de départ pour comparer les tâches entre elles.', caution: 'Le résultat est une estimation interne : il ne remplace ni une observation du processus ni la validation de l’équipe.', relatedLabel: 'Cadrer un processus avant de l’automatiser', relatedHref: '/fr/blog/automatisation-processus-ia-pme-checklist' },
  'prompts-metier': { image: '/images/iapmesuisse-outil-prompts-metier-20260909.png', alt: 'Responsable de PME suisse préparant une consigne de travail précise.', answer: 'Préparez une consigne claire, adaptée à votre métier, pour obtenir un brouillon plus exploitable dès le premier essai.', method: 'Ajoutez le contexte, le destinataire, le ton, le format attendu et les limites à respecter. Relisez toujours le résultat avant usage.', caution: 'Ne saisissez pas de données sensibles, de secrets d’affaires ou de documents clients dans un assistant non autorisé par votre entreprise.', relatedLabel: 'Consulter les logiciels IA utiles aux PME', relatedHref: '/fr/outils-ia' },
  'relance-devis': { image: '/images/iapmesuisse-outil-relance-devis-20260909.png', alt: 'Artisan suisse relisant une proposition avant une relance client.', answer: 'Transformez les informations de votre devis en une relance courte, polie et simple à personnaliser.', method: 'Précisez le contexte, le délai, la prochaine étape et le ton. Le prompt propose un brouillon à adapter à la relation commerciale.', caution: 'Vérifiez les faits, les pièces jointes et les engagements avant l’envoi. L’outil ne décide pas à votre place.', relatedLabel: 'Découvrir l’agent IA de vente et de prospection', relatedHref: '/fr/blog/agent-ia-vente-prospection-suisse' },
  'choisir-automatisation': { image: '/images/iapmesuisse-outil-choisir-automatisation-20260909.png', alt: 'Équipe de PME suisse classant des tâches répétitives par priorité.', answer: 'Choisissez une première tâche automatisable selon sa répétition, sa clarté et les risques qu’elle comporte.', method: 'Commencez par une tâche fréquente, documentée et facile à contrôler. Un essai limité produit plus d’enseignements qu’un chantier trop large.', caution: 'Une tâche impliquant une décision réglementée, contractuelle ou RH demande une validation humaine explicite.', relatedLabel: 'Lire la checklist d’automatisation des processus', relatedHref: '/fr/blog/automatisation-processus-ia-pme-checklist' },
  'charge-emails': { image: '/images/iapmesuisse-outil-charge-emails-20260909.png', alt: 'Employée de PME suisse évaluant son temps consacré aux courriels.', answer: 'Mesurez la charge récurrente des courriels pour décider si un modèle, une procédure ou un assistant mérite un essai.', method: 'Estimez le volume et le temps moyen sur une semaine représentative. Comparez ensuite les catégories de messages les plus répétitives.', caution: 'N’utilisez jamais le calcul pour réduire une situation complexe à un seul chiffre : la qualité de réponse et le contrôle restent essentiels.', relatedLabel: 'Préparer un brief d’automatisation', relatedHref: '/fr/ressources#brief-automatisation' },
  'reunion': { image: '/images/iapmesuisse-outil-reunion-20260909.png', alt: 'Réunion de travail dans une PME suisse autour de prochaines actions.', answer: 'Préparez un ordre du jour orienté décisions, responsables et prochaines actions pour éviter les réunions sans suite.', method: 'Donnez l’objectif, les participants et les décisions attendues. Utilisez ensuite le texte comme base de préparation, pas comme compte rendu automatique.', caution: 'Conservez un temps de relecture pour vérifier les décisions et les responsabilités avant diffusion.', relatedLabel: 'Faire le point avec le quiz de maturité IA', relatedHref: '/fr/quiz/maturite-ia' },
  'procedure': { image: '/images/iapmesuisse-outil-procedure-20260909.png', alt: 'Employée de PME suisse documentant une procédure de travail.', answer: 'Posez une première procédure interne pour rendre une tâche transmissible, vérifiable et plus simple à améliorer.', method: 'Décrivez le déclencheur, les étapes, la personne responsable, les exceptions et la preuve de fin de tâche.', caution: 'Testez la procédure avec une personne qui ne l’a pas écrite : elle révèle souvent les étapes implicites.', relatedLabel: 'Cadrer un processus avant son automatisation', relatedHref: '/fr/blog/automatisation-processus-ia-pme-checklist' },
  'avis-client': { image: '/images/iapmesuisse-outil-avis-client-20260909.png', alt: 'Dirigeant suisse écoutant attentivement une cliente dans son entreprise.', answer: 'Préparez une réponse professionnelle à un avis client, avec un ton calme et une prochaine étape claire.', method: 'Fournissez les faits vérifiés, ce qui peut être proposé et ce qui doit encore être contrôlé. L’outil prépare un brouillon de réponse.', caution: 'Ne publiez pas d’information personnelle ou confidentielle dans une réponse publique. En cas de litige, faites valider le texte.', relatedLabel: 'Préparer une FAQ métier à partir des questions récurrentes', relatedHref: '/fr/ressources#faq' },
  'faq': { image: '/images/iapmesuisse-outil-faq-20260909.png', alt: 'Responsable de PME suisse organisant les questions fréquentes de ses clients.', answer: 'Transformez les vraies questions de vos clients en réponses utiles, faciles à relire et à faire évoluer.', method: 'Partez des appels, courriels et demandes récurrentes. Une bonne FAQ répond d’abord à une question réelle avant de présenter votre activité.', caution: 'Évitez les promesses générales. Gardez les réponses factuelles et mettez à jour les informations pratiques dès qu’elles changent.', relatedLabel: 'Lire le guide des outils IA gratuits pour PME', relatedHref: '/fr/blog/outils-ia-gratuits-pme-suisse-top-15-2026' },
  'essai-ia': { image: '/images/iapmesuisse-outil-essai-ia-20260909.png', alt: 'Dirigeant de PME suisse comparant un travail avant et après un essai IA.', answer: 'Évaluez un essai IA à partir du temps, de la qualité, des corrections et de la capacité de l’équipe à reprendre la main.', method: 'Comparez une même tâche avant et après, sur un petit périmètre. Notez ce qui a réellement changé plutôt que de supposer un gain.', caution: 'Un essai utile inclut les corrections, les exceptions et le temps de contrôle ; ne retenez pas uniquement le résultat le plus rapide.', relatedLabel: 'Comprendre la méthode de calcul du ROI de l’IA', relatedHref: '/fr/blog/roi-intelligence-artificielle-pme-suisse' },
  'charte-ia': { image: '/images/iapmesuisse-outil-charte-ia-20260909.png', alt: 'Équipe de PME suisse échangeant sur un cadre d’utilisation responsable de l’IA.', answer: 'Préparez un cadre simple pour aider l’équipe à savoir quels usages sont permis, à vérifier et à escalader.', method: 'Définissez les outils autorisés, les données à exclure, le contrôle humain, les rôles et la manière de signaler un doute.', caution: 'Cette trame doit être adaptée à votre activité et à vos obligations. Elle ne remplace pas un avis juridique ou de conformité.', relatedLabel: 'Consulter la checklist nLPD et AI Act', relatedHref: '/fr/ressources/checklist-nlpd-ai-act' },
  'brief-automatisation': { image: '/images/iapmesuisse-outil-brief-automatisation-20260909.png', alt: 'Responsable de PME suisse cartographiant un flux de travail avant automatisation.', answer: 'Rassemblez les éléments nécessaires pour expliquer un processus sans ambiguïté avant de demander une automatisation.', method: 'Décrivez le déclencheur, les entrées, les étapes, les outils actuels, les exceptions et le résultat attendu.', caution: 'Un bon brief indique aussi ce que le système ne doit jamais faire et qui valide les cas inhabituels.', relatedLabel: 'Voir comment choisir la première tâche à automatiser', relatedHref: '/fr/ressources#choisir-automatisation' },
  'agent-sur-mesure': { image: '/images/iapmesuisse-outil-agent-sur-mesure-20260909.png', alt: 'Dirigeant de PME suisse et consultante examinant un processus pour un agent IA sur mesure.', answer: 'Identifiez le type d’agent IA qui peut assister votre entreprise à partir d’un besoin réel, d’un processus et de vos contraintes.', method: 'Le diagnostic utilise votre secteur, les tâches, les données concernées et le niveau de validation requis pour proposer une piste de cadrage.', caution: 'Le résultat est une orientation. Un rappel n’est transmis qu’après votre consentement explicite, afin d’examiner le besoin avec vous.', relatedLabel: 'Découvrir comment cadrer un agent IA de vente', relatedHref: '/fr/blog/agent-ia-vente-prospection-suisse' },
};
