export type PromptTemplate = {
  id: string; title: string; purpose: string; fields: readonly string[];
  instruction: string; reviewChecklist: readonly string[];
};
export const PROMPT_CATALOG: readonly PromptTemplate[] = [
  { id: 'relance-devis', title: 'Relancer un devis sans réponse', purpose: 'Obtenir une prochaine étape claire.',
    fields: ['besoinClient', 'dateEnvoi', 'dernierEchange', 'prochaineEtape'],
    instruction: 'Prépare un email de moins de 120 mots, une variante détaillée et un script d’appel. Rappelle uniquement le besoin et les échanges fournis. Termine par une seule question permettant au client de choisir la prochaine étape. Ne déduis pas la raison de son silence et n’invente aucune urgence ni remise.',
    reviewChecklist: ['Vérifier la date et le dernier échange.', 'Retenir un seul canal adapté à la relation.', 'Confirmer la prochaine étape avant envoi.'] },
  { id: 'reactivation-client', title: 'Reprendre contact avec un ancien client', purpose: 'Vérifier si un besoin a évolué.',
    fields: ['relationAnterieure', 'dernierContact', 'motifReprise', 'prochaineEtape'],
    instruction: 'Rédige un message bref qui rappelle la relation décrite puis explique le motif réel de la reprise de contact. Pose une question sur le besoin actuel. Ne prétends pas connaître la situation récente du client et ne présente pas une ancienne préférence comme toujours valable.',
    reviewChecklist: ['Vérifier que la reprise de contact est appropriée.', 'Retirer les informations devenues obsolètes.'] },
  { id: 'rendez-vous-prospect', title: 'Préparer un rendez-vous prospect', purpose: 'Comprendre le besoin avant de proposer une solution.',
    fields: ['informationsConfirmees', 'objectifRendezVous', 'dureeDisponible'],
    instruction: 'Propose un déroulé adapté à la durée fournie : ouverture, questions de découverte, clarification des contraintes et conclusion. Sépare faits connus et hypothèses à vérifier. Prépare des questions sur le processus actuel et les critères de décision, sans inventer de besoin ni de budget.',
    reviewChecklist: ['Distinguer informations confirmées et hypothèses.', 'Vérifier que la durée du déroulé est cohérente.'] },
  { id: 'objection', title: 'Répondre à une objection commerciale', purpose: 'Clarifier le frein exprimé.',
    fields: ['objectionExacte', 'contexteEchange', 'faitsDisponibles', 'limitesEngagement'],
    instruction: 'Reformule l’objection sans la minimiser. Propose une question de clarification et une réponse fondée sur les faits disponibles. Indique ce qui doit être vérifié avant de répondre. Ne promets aucun avantage, délai ou résultat absent des informations fournies.',
    reviewChecklist: ['Respecter le sens de l’objection.', 'Faire valider tout engagement.'] },
  { id: 'reclamation', title: 'Préparer une réponse à une réclamation', purpose: 'Répondre tout en distinguant les faits à vérifier.',
    fields: ['reclamationAnonymisee', 'faitsConfirmes', 'pointsInconnus', 'actionAutorisee'],
    instruction: 'Prépare un brouillon de réponse client puis une liste de vérifications internes. Reconnais la difficulté décrite sans attribuer de responsabilité non établie. Cite seulement les actions autorisées. Ne transforme pas une hypothèse sur l’incident en explication certaine.',
    reviewChecklist: ['Vérifier les faits et responsabilités.', 'Retirer les données personnelles inutiles.', 'Approuver les actions proposées.'] },
  { id: 'avis-client', title: 'Répondre à un avis négatif', purpose: 'Préparer une réponse publique mesurée.',
    fields: ['avisAnonymise', 'faitsConfirmes', 'canalContactAutorise'],
    instruction: 'Rédige une réponse publique courte et un point de suivi interne séparé. Ne révèle aucun détail du dossier, ne conteste pas des faits sans preuve et n’invente pas de compensation. Invite à poursuivre par le canal fourni lorsque cela aide à résoudre la situation.',
    reviewChecklist: ['Ne révéler aucune information de dossier.', 'Vérifier le canal de contact.', 'Relire le ton avant publication.'] },
  { id: 'pieces-manquantes', title: 'Demander des documents manquants', purpose: 'Obtenir les pièces déjà identifiées par le responsable.',
    fields: ['dossierAnonymise', 'piecesAttendues', 'piecesRecues', 'echeanceConfirmee'],
    instruction: 'Prépare une demande claire listant les pièces attendues qui ne figurent pas parmi les pièces reçues. Signale les intitulés ambigus et les doublons possibles pour vérification humaine. Conserve uniquement l’échéance confirmée. Ne conclus pas que le dossier sera juridiquement complet.',
    reviewChecklist: ['Valider la liste avec le responsable.', 'Vérifier les doublons et l’échéance.'] },
  { id: 'faq', title: 'Préparer une FAQ client', purpose: 'Répondre aux questions effectivement reçues.',
    fields: ['questionsRecues', 'reponsesValidees', 'limitesPrestations'],
    instruction: 'Regroupe les questions de même intention, puis rédige des réponses courtes à partir des informations validées. Sépare les réponses publiables des points incomplets. N’invente aucune garantie, prestation ni règle. Les questions auxquelles les données ne répondent pas doivent rester à compléter.',
    reviewChecklist: ['Faire valider chaque réponse.', 'Conserver les limites des prestations.', 'Prévoir le responsable des mises à jour.'] },
  { id: 'email-allemand', title: 'Adapter un email en allemand standard suisse', purpose: 'Préparer une communication professionnelle à faire relire.',
    fields: ['texteSource', 'destinataireEtContexte', 'termesAConserver'],
    instruction: 'Adapte le texte source en allemand standard utilisé en Suisse, sans dialecte. Préserve dates, références, faits et engagements. Présente les ambiguïtés en français et ne les résous pas arbitrairement. Fournis une liste des éléments à vérifier avec une personne compétente ; ce travail ne constitue pas une traduction certifiée.',
    reviewChecklist: ['Comparer dates, références et engagements au texte source.', 'Faire relire les communications à conséquences importantes.'] },
  { id: 'suivi-rendez-vous', title: 'Rédiger un suivi après rendez-vous', purpose: 'Confirmer ce qui a réellement été convenu.',
    fields: ['notesAnonymisees', 'decisionsConfirmees', 'prochainesActions'],
    instruction: 'Prépare un email de suivi distinguant les décisions confirmées, les propositions encore ouvertes et les prochaines actions. N’invente pas d’accord. Pour une échéance ou un responsable absent, indique à confirmer. Termine par une demande de correction si le récapitulatif ne reflète pas les échanges.',
    reviewChecklist: ['Vérifier la distinction accord/proposition.', 'Confirmer responsables et dates.'] },
  { id: 'notes-actions', title: 'Transformer des notes en plan d’action', purpose: 'Faire ressortir les décisions et responsabilités.',
    fields: ['notesAnonymisees', 'objectifSuivi'],
    instruction: 'Structure les notes en décisions prises, actions, responsables, échéances et questions ouvertes. Utilise à confirmer pour une information absente. Ne transforme pas une idée citée dans les notes en décision prise. Liste en fin de document les points qui empêchent l’exécution.',
    reviewChecklist: ['Comparer chaque décision aux notes.', 'Faire confirmer les responsabilités manquantes.'] },
  { id: 'reunion', title: 'Préparer une réunion de direction', purpose: 'Organiser un échange autour d’une décision.',
    fields: ['decisionAttendue', 'participantsEtRoles', 'informationsDisponibles', 'dureeDisponible'],
    instruction: 'Propose un ordre du jour avec les points d’information, de discussion et de décision. Répartis la durée disponible sans la dépasser. Identifie les documents à préparer et les questions encore ouvertes. Fournis une trame de relevé des décisions sans présumer du résultat de la réunion.',
    reviewChecklist: ['Confirmer que les décideurs sont présents.', 'Vérifier la durée totale.', 'Préparer les informations nécessaires.'] },
  { id: 'procedure', title: 'Préparer une procédure interne', purpose: 'Rendre une tâche transmissible.',
    fields: ['declencheur', 'etapesActuelles', 'rolesEtAcces', 'exceptions', 'resultatAttendu'],
    instruction: 'Ordonne le processus en déclencheur, prérequis, étapes, responsable de chaque étape, exceptions et contrôle final. Signale les accès et validations manquants. Ne crée pas de règle interne non fournie. Prépare un exemple de vérification à faire réaliser par une personne connaissant le travail.',
    reviewChecklist: ['Faire relire par le responsable métier.', 'Tester la procédure sur un cas adapté.', 'Vérifier les exceptions.'] },
  { id: 'taches-repetitives', title: 'Repérer les tâches répétitives', purpose: 'Définir un premier périmètre d’essai.',
    fields: ['tachesEtFrequences', 'dureesObservees', 'exceptions', 'consequencesErreur'],
    instruction: 'Compare les tâches selon leur fréquence, leurs règles, la stabilité des entrées et les conséquences d’une erreur. Sépare automatisation classique, assistance avec relecture et décision humaine. Explique chaque orientation sans inventer de score scientifique ni de gain garanti. Propose une observation à réaliser avant l’essai.',
    reviewChecklist: ['Vérifier les durées et les exceptions.', 'Conserver les décisions sensibles sous responsabilité humaine.'] },
  { id: 'fournisseurs', title: 'Comparer des propositions fournisseurs', purpose: 'Comparer un périmètre et des engagements vérifiables.',
    fields: ['besoinEtCriteres', 'propositionsAnonymisees', 'contraintes'],
    instruction: 'Construis une comparaison des périmètres, livrables, dépendances, exclusions et engagements explicitement décrits. Marque non précisé lorsqu’une information manque. Ne désigne pas de gagnant sans critères validés et données comparables. Prépare les questions à envoyer séparément aux fournisseurs pour lever les ambiguïtés.',
    reviewChecklist: ['Vérifier les périmètres comparés.', 'Valider les critères avant arbitrage.', 'Contrôler chaque fait dans les propositions.'] },
  { id: 'accueil-collaborateur', title: 'Préparer l’accueil d’un collaborateur', purpose: 'Organiser les accès, les informations et l’accompagnement.',
    fields: ['role', 'dateArrivee', 'tachesAttendues', 'personnesReferentes', 'accesNecessaires'],
    instruction: 'Prépare un parcours d’accueil avec actions avant l’arrivée, premières tâches, personnes à rencontrer et points de suivi. Sépare les accès demandés des accès déjà validés. Ne génère pas d’identifiants, de mots de passe ni de règles RH supposées. Signale les responsables et échéances à confirmer.',
    reviewChecklist: ['Faire valider les accès.', 'Confirmer les personnes référentes.', 'Vérifier les règles internes applicables.'] },
  { id: 'tableau-bord', title: 'Structurer un tableau de bord', purpose: 'Choisir des indicateurs associés à des décisions.',
    fields: ['objectifPilotage', 'donneesDisponibles', 'decisionsAPrendre', 'frequenceSuivi'],
    instruction: 'Propose un nombre limité d’indicateurs utiles aux décisions décrites. Pour chacun, indique définition, unité, source, formule et limites. N’invente pas de cible ni de donnée manquante. Sépare indicateurs calculables immédiatement et indicateurs nécessitant une collecte complémentaire.',
    reviewChecklist: ['Vérifier les unités et sources.', 'Associer chaque indicateur à une décision.', 'Ne pas confondre zéro et donnée absente.'] },
  { id: 'ecarts-indicateurs', title: 'Examiner des écarts dans des indicateurs', purpose: 'Distinguer constats et explications à tester.',
    fields: ['donneesEtUnites', 'periodesComparees', 'definitionsIndicateurs', 'changementsConnus'],
    instruction: 'Décris les écarts absolus et relatifs lorsque les dénominateurs le permettent. Ne calcule pas un taux à partir d’une référence nulle. Sépare constats, hypothèses et vérifications nécessaires. Signale périodes, volumes ou définitions non comparables. Ne présente pas une corrélation comme une cause.',
    reviewChecklist: ['Recalculer les chiffres importants.', 'Contrôler les dénominateurs.', 'Vérifier la comparabilité des périodes.'] },
  { id: 'brief-automatisation', title: 'Préparer un brief d’automatisation', purpose: 'Décrire le processus avant de choisir une solution.',
    fields: ['processusActuel', 'logiciels', 'donneesEtAcces', 'exceptions', 'resultatAttendu'],
    instruction: 'Prépare un brief avec déclencheur, entrées, étapes, sorties, validations humaines, exceptions et critères d’acceptation. Liste les questions d’intégration et de reprise après erreur. Ne suppose pas qu’une API ou une autorisation existe. Distingue périmètre connu et points à confirmer avant réalisation.',
    reviewChecklist: ['Valider les accès et dépendances.', 'Définir les cas de test.', 'Prévoir la reprise et la responsabilité humaine.'] },
  { id: 'bilan-essai', title: 'Évaluer les résultats d’un essai IA', purpose: 'Lire une comparaison avant/après sans exagérer sa portée.',
    fields: ['mesuresAvantApres', 'volumesEtTypesTaches', 'controleEtCorrections', 'erreursObservees', 'changementsConcomitants'],
    instruction: 'Compare le temps complet par tâche et le taux de tâches comportant une erreur. Sépare mise en place et usage récurrent, puis indique le bilan sur la période observée. Signale les différences de difficulté et de volume. Formule une conclusion descriptive, les limites et la prochaine mesure utile, sans attribuer automatiquement le résultat à l’IA.',
    reviewChecklist: ['Vérifier les durées complètes.', 'Comparer des tâches de difficulté proche.', 'Examiner séparément vitesse et qualité.'] },
];
export const CHARTER_KIT: PromptTemplate = {
  id: 'charte-ia', title: 'Préparer une charte d’utilisation de l’IA',
  purpose: 'Réunir les décisions internes dans un brouillon à faire valider.',
  fields: ['usagesEnvisages', 'outilsExamines', 'donneesConcernees', 'validationHumaine', 'responsable'],
  instruction: 'Prépare une trame de travail : périmètre, usages examinés, décisions sur les outils, données, validations, incidents et révision. Pour chaque règle absente, demande une décision au lieu d’inventer une politique. Liste les points à examiner avec les responsables compétents. Cite comme ressource le modèle du canton de Genève : https://www.ge.ch/document/modele-charte-intelligence-artificielle-destination-entreprises . Présente le résultat comme un brouillon ; ne certifie aucune conformité et ne fournis aucun avis juridique individualisé.',
  reviewChecklist: ['Consulter le modèle officiel et son guide.', 'Valider les décisions avec les responsables compétents.', 'Nommer le responsable des mises à jour.'],
};
export const SECTORS = {
  fiduciaire: 'Préparation et suivi de dossiers ; la validation du dossier reste au professionnel responsable.',
  artisan: 'Préparation et suivi des interventions ; conserver les contraintes réelles du chantier.',
  garage: 'Suivi des demandes et interventions ; ne pas inventer de diagnostic technique.',
  immobilier: 'Organisation des visites et dossiers ; ne pas inventer les caractéristiques d’un bien.',
  hotellerie: 'Accueil et suivi des demandes ; confirmer les disponibilités et services avant engagement.',
  services: 'Organisation et relation client ; conserver le périmètre de prestation validé.',
} as const;